# Generated by Django 3.2.2 on 2021-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='本の名前')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('price', models.CharField(max_length=200, verbose_name='価格')),
            ],
        ),
    ]
